### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by fairuzabd** [Thaza-Kun/samudra#5]
Poetry v 1.1.14
Python v 3.10.5
Windows 10

Error bila run guna poetry run python ./samudra/serve.py

D:\samudra>poetry run python ./samudra/serve.py
Traceback (most recent call last):
  File "D:\samudra\samudra\serve.py", line 3, in <module>
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'

Module dah install. Sebab bila run direct python ./samudra/serve.py

D:\samudra>python samudra/serve.py
Traceback (most recent call last):
  File "D:\samudra\samudra\serve.py", line 8, in <module>
    from samudra.conf.server.cors_policy import ALLOWED_ORIGINS
ModuleNotFoundError: No module named 'samudra'

ALLOWED_ORIGINS ni merujuk kepada localhost:3000 kan? Masih tak nampak perkaitan lagi kat mana untuk selesaikan.

**Comment by Thaza-Kun** [comment]
Pelik, dalam #1 tak jumpa uvicorn sebab tak guna `poetry run python ./samudra/serve.py` tapi kat sini tak jumpa uvicorn walaupun dah guna poetry.

Aku syak, mungkin sebab kau pakai Python 3.10?

Ada beberapa pakej yang tak dapat dipasang secara elok bila pakai Python 3.10.

Nanti aku cuba fresh install pakai Python 3.10.5 tengok macam mana.

**Comment by Thaza-Kun** [comment]
> ALLOWED_ORIGINS ni merujuk kepada localhost:3000 kan? Masih tak nampak perkaitan lagi kat mana untuk selesaikan.

Ya, ALLOWED_ORIGINS ni merujuk kepada localhost:3000 untuk membenarkan bahagian frontend berkomunikasi dengan backend ini sewaktu testing. Senarai itu tak seharusnya rosakkan apa2 bahagian.

**Comment by fairuzabd** [comment]
> > ALLOWED_ORIGINS ni merujuk kepada localhost:3000 kan? Masih tak nampak perkaitan lagi kat mana untuk selesaikan.
> 
> Ya, ALLOWED_ORIGINS ni merujuk kepada localhost:3000 untuk membenarkan bahagian frontend berkomunikasi dengan backend ini sewaktu testing. Senarai itu tak seharusnya rosakkan apa2 bahagian.

yang ini rasanya bole faham sebab tak ada server instance running at that port.

**Comment by fairuzabd** [comment]
cuba run di Ubuntu 20.04.4 LTS, poetry 1.1.14, Python 3.8.10

$ poetry run python3 samudra/serve.py
Traceback (most recent call last):
  File "samudra/serve.py", line 3, in <module>
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'

run direct selepas clone, ini yang keluar. lepas install uvicorn dan fastapi (error yang kedua), masih lagi isu yang sama.

kalau direct run python3 serve.py,

$ python3 serve.py
Traceback (most recent call last):
  File "serve.py", line 8, in <module>
    from samudra.conf.server.cors_policy import ALLOWED_ORIGINS
ModuleNotFoundError: No module named 'samudra'

masih lagi blur kat mana yang bermasalah sekarang ni. 

mungkin machine? atau ada module kat mana-mana yang silap ref.

**Comment by Thaza-Kun** [comment]
Kalau buat `poetry show --tree` keluar apa?

**Comment by Thaza-Kun** [comment]
> Traceback (most recent call last):
> File "serve.py", line 8, in
> from samudra.conf.server.cors_policy import ALLOWED_ORIGINS
> ModuleNotFoundError: No module named 'samudra'

Kalau ada masalah macam ini, cuba ganti semua `from samudra.module_name` menjadi `from module_name` dalam fail `serve.py`. Jadi, dia jadi macam ini dekat kepala `serve.py`:

```python
from conf.server.cors_policy import ALLOWED_ORIGINS
from server.setup import check_tables
from server import lemmas, konseps
```

**Comment by fairuzabd** [comment]
> 

$ poetry show --tree
cryptography 37.0.4 cryptography is a package which provides cryptographic recipes and primitives to Python developers.

  UnicodeEncodeError

  'charmap' codec can't encode characters in position 0-2: character maps to <undefined>

  at ~\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py:19 in encode

**Comment by fairuzabd** [comment]
maaf. masalah terminal. guna terminal lain baru keluar yang ni. 

D:\samudra>poetry show --tree
cryptography 37.0.4 cryptography is a package which provides cryptographic recipes and primitives to Python developers.
`-- cffi >=1.12
    `-- pycparser *
fastapi 0.79.0 FastAPI framework, high performance, easy to learn, fast to code, ready for production
|-- pydantic >=1.6.2,<1.7 || >1.7,<1.7.1 || >1.7.1,<1.7.2 || >1.7.2,<1.7.3 || >1.7.3,<1.8 || >1.8,<1.8.1 || >1.8.1,<2.0.0
|   `-- typing-extensions >=3.7.4.3
`-- starlette 0.19.1
    |-- anyio >=3.4.0,<5
    |   |-- idna >=2.8
    |   `-- sniffio >=1.1
    `-- typing-extensions >=3.10.0
openpyxl 3.0.10 A Python library to read/write Excel 2010 xlsx/xlsm files
`-- et-xmlfile *
pandas 1.4.3 Powerful data structures for data analysis, time series, and statistics
|-- numpy >=1.18.5
|-- numpy >=1.19.2
|-- numpy >=1.20.0
|-- numpy >=1.21.0
|-- python-dateutil >=2.8.1
|   `-- six >=1.5
`-- pytz >=2020.1
peewee 3.15.1 a little orm
psycopg2 2.9.3 psycopg2 - Python-PostgreSQL Database Adapter
pydantic 1.9.1 Data validation and settings management using python type hints
`-- typing-extensions >=3.7.4.3
pymysql 1.0.2 Pure Python MySQL Driver
pytest 5.4.3 pytest: simple powerful testing with Python
|-- atomicwrites >=1.0
|-- attrs >=17.4.0
|-- colorama *
|-- more-itertools >=4.0.0
|-- packaging *
|   `-- pyparsing >=2.0.2,<3.0.5 || >3.0.5
|-- pluggy >=0.12,<1.0
|-- py >=1.5.0
`-- wcwidth *
python-dotenv 0.20.0 Read key-value pairs from a .env file and set them as environment variables
pytomlpp 1.0.11 A python wrapper for toml++
uvicorn 0.18.2 The lightning-fast ASGI server.
|-- click >=7.0
|   `-- colorama *
`-- h11 >=0.8

python 3.10 fresh install sebab tu tak banyak package. 

D:\samudra>pip list
Package           Version
----------------- -------
anyio             3.6.1
click             8.1.3
colorama          0.4.5
fastapi           0.79.0
h11               0.13.0
idna              3.3
pip               22.2.1
pydantic          1.9.1
setuptools        58.1.0
sniffio           1.2.0
starlette         0.19.1
typing_extensions 4.3.0
uvicorn           0.18.2

mungkin ada dependencies yang tak perasan perlu ada.

**Comment by Thaza-Kun** [comment]
Kalau macam tu, cuba senaraikan semua arahan selengkap mungkin dari mula install poetry, klon repo, semua tu sampailah ke tempat yang keluar error. Nak cuba replicate sebaik mungkin nak tengok silapnya di mana.

(Letak arahan dalam \`arahan\` supaya senang sikit baca. Contoh:
`$ git clone link .`

`$ poetry install`
)

**Comment by fairuzabd** [comment]
1. Fresh install Python dari installer download dari [Download [Windows installer (64-bit)](https://www.python.org/ftp/python/3.10.5/python-3.10.5-amd64.exe) version 3.10.5
2. Install poetry guna `curl -sSL https://install.python-poetry | python -` ikut guide dari docs poetry
3. `git clone https://github.com/Thaza-kun/samudra.git`
4. `poetry run python ./samudra/serve.py`

```
Traceback (most recent call last):
  File "D:\samudra\samudra\serve.py", line 3, in <module>
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'
```

5. `python ./samudra/serve.py`

```
Traceback (most recent call last):
  File "D:\samudra\samudra\serve.py", line 9, in <module>
    from server.setup import check_tables
  File "D:\samudra\samudra\server\__init__.py", line 1, in <module>
    from .routes import lemmas, konseps
  File "D:\samudra\samudra\server\routes\lemmas.py", line 6, in <module>
    from samudra import models, schemas
ModuleNotFoundError: No module named 'samudra'
```

ini selepas cuba cadangan [ini](https://github.com/Thaza-Kun/samudra/issues/5#issuecomment-1202248374) dan juga `pip intstall *` mana-mana package yang tiada. Mungkin ada yang tertinggal lagi `samudra.module` yang lain. 

6. Bila buat `poetry show -tree`
```
cryptography 37.0.4 cryptography is a package which provides cryptographic recipes and primitives to Python developers.
`-- cffi >=1.12
    `-- pycparser *
fastapi 0.79.0 FastAPI framework, high performance, easy to learn, fast to code, ready for production
|-- pydantic >=1.6.2,<1.7 || >1.7,<1.7.1 || >1.7.1,<1.7.2 || >1.7.2,<1.7.3 || >1.7.3,<1.8 || >1.8,<1.8.1 || >1.8.1,<2.0.0
|   `-- typing-extensions >=3.7.4.3
`-- starlette 0.19.1
    |-- anyio >=3.4.0,<5
    |   |-- idna >=2.8
    |   `-- sniffio >=1.1
    `-- typing-extensions >=3.10.0
openpyxl 3.0.10 A Python library to read/write Excel 2010 xlsx/xlsm files
`-- et-xmlfile *
pandas 1.4.3 Powerful data structures for data analysis, time series, and statistics
|-- numpy >=1.18.5
|-- numpy >=1.19.2
|-- numpy >=1.20.0
|-- numpy >=1.21.0
|-- python-dateutil >=2.8.1
|   `-- six >=1.5
`-- pytz >=2020.1
peewee 3.15.1 a little orm
psycopg2 2.9.3 psycopg2 - Python-PostgreSQL Database Adapter
pydantic 1.9.1 Data validation and settings management using python type hints
`-- typing-extensions >=3.7.4.3
pymysql 1.0.2 Pure Python MySQL Driver
pytest 5.4.3 pytest: simple powerful testing with Python
|-- atomicwrites >=1.0
|-- attrs >=17.4.0
|-- colorama *
|-- more-itertools >=4.0.0
|-- packaging *
|   `-- pyparsing >=2.0.2,<3.0.5 || >3.0.5
|-- pluggy >=0.12,<1.0
|-- py >=1.5.0
`-- wcwidth *
python-dotenv 0.20.0 Read key-value pairs from a .env file and set them as environment variables
pytomlpp 1.0.11 A python wrapper for toml++
uvicorn 0.18.2 The lightning-fast ASGI server.
|-- click >=7.0
|   `-- colorama *
`-- h11 >=0.8
```
dan `pip list`
```
Package           Version
----------------- -------
anyio             3.6.1
click             8.1.3
colorama          0.4.5
fastapi           0.79.0
h11               0.13.0
idna              3.3
peewee            3.15.1
pip               22.2.1
pydantic          1.9.1
python-dotenv     0.20.0
pytomlpp          1.0.11
setuptools        58.1.0
sniffio           1.2.0
starlette         0.19.1
typing_extensions 4.3.0
uvicorn           0.18.2
```

**Comment by icedcoffeeee** [comment]
> 3. `git clone https://github.com/Thaza-kun/samudra.git`
> 4. `poetry run python ./samudra/serve.py`

@fairuzabd nampaknya selepas `git clone`, tak dilaksanakan `poetry install`. Untuk `poetry run` menggunakan persekitaran (environment) folder `samudera` ini, `poetry` perlu memasang terlebih dahulu pakej-pakej dalam fail `poetry.lock`.

**Comment by Thaza-Kun** [comment]
Oh haah. Bahagian `poetry install` tu penting. Sebab itulah tak jumpa modul uvicorn. Ingatkan dah buat (itu yang rasa pelik).

**Comment by Thaza-Kun** [comment]
Barangkali arahan dalam `README` sedikit mengelirukan. Nanti saya ubah supaya lebih jelas langkah-langkahnya.

**Comment by fairuzabd** [comment]
Ya betul. Mintak maaf banyak-banyak. Terlepas pandang item 3 sampai dua hari tak selesai masalah. Terima kasih bersabar layan noob. 😄 

cadangan [ini](https://github.com/Thaza-Kun/samudra/issues/5#issuecomment-1202248374) memang menjadi. Tapi kena cari semua sekali yang ada `samudra.module_name` dalam semua fail. Agak banyak juga. 

Saya cadangkan tambahan untuk README seperti di bawah. Terima kasih sekali lagi. Saya tutup issue ini.

### Pemasangan

1. Guna Python 3.8 atau lebih tinggi.
2. Digalakkan guna [poetry](https://python-poetry.org/docs/). Ikut arahan pemasangan di laman. 
3. Klon kod sumber `git clone https://github.com/Thaza-kun/samudra.git`.
4. `cd samudra` dan masukkan arahan `poetry install`. Langkah penting untuk memastikan semua *dependencies* dipasang.

**Comment by Thaza-Kun** [comment]
Tidak mengapa. Perisian yang baik memerlukan dokumentasi yang baik. Kesilapan-kesilapan kecil seperti ini bantu memperbaiki dokumentasi. Aku sudah baiki README dalam 4d01fc2b4f8da4c45dc1f5f118f7d69578ae7b85.

---

> cadangan https://github.com/Thaza-Kun/samudra/issues/5#issuecomment-1202248374 memang menjadi. Tapi kena cari semua sekali yang ada samudra.module_name dalam semua fail. Agak banyak juga.

Setelah difikirkan semula, cadangan :point_up_2: sebab fail python itu dilaksanakan dari dalam fail `./samudra/`. Benda ini tak patut. (`.` merujuk kepada direktori induk atau direktori paling luar bagi sesuatu projek (bahasa inggerisnya _root directory_)). Bila masuk ke dalam `./samudra/` kemudian buat `python ./serve.py` memang fail2 itu tak jumpa modul `samudra` sebab `samudra` itu merujuk kepada folder samudra yang dimasuki tadi.

Maksudnya begini:
```shell
# RUN poetry run python ./samudra/serve.py dari sini
samudra # <- Ini ROOT
├───data
├───docs
├───samudra # JANGAN RUN python ./serve.py dari sini
│   │ # ^ inilah modul samudra yang dirujuk dalam from samudra import ...
│   ├───conf
│   ├───core
│   ├───models
│   ├───schemas
│   ├───server
│   └───serve.py
└───tests
```

**Comment by fairuzabd** [comment]
Ada logiknya tapi dia tak menjelaskan kenapa bila run `D:\samudra>poetry run python ./samudra/serve.py' dia jadi macam ni
```
INFO:     Will watch for changes in these directories: ['D:\\samudra']
INFO:uvicorn.error:Will watch for changes in these directories: ['D:\\samudra']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [17500] using StatReload
INFO:uvicorn.error:Started reloader process [17500] using StatReload
INFO:     Started server process [19476]
INFO:uvicorn.error:Started server process [19476]
INFO:     Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.
INFO:     Application startup complete.
INFO:uvicorn.error:Application startup complete.
INFO:     Stopping reloader process [17500]
INFO:uvicorn.error:Stopping reloader process [17500]
```

tapi bila kita run `D:\samudra\samudra>python serve.py` (run dari subfolder `samudara`), dia akan jadi
```
Traceback (most recent call last):
  File "D:\samudra\samudra\serve.py", line 8, in <module>
    from conf.server.cors_policy import ALLOWED_ORIGINS
  File "D:\samudra\samudra\conf\__init__.py", line 3, in <module>
    from .database.core import Database
  File "D:\samudra\samudra\conf\database\core.py", line 9, in <module>
    from conf.setup import settings
  File "D:\samudra\samudra\conf\setup.py", line 4, in <module>
    settings = toml.load('conf.toml')
  File "C:\Users\Fairuz\AppData\Local\Programs\Python\Python310\lib\site-packages\pytomlpp\_io.py", line 67, in load
    with open(fl, mode=mode) as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'conf.toml'
```

yang mana logik kerana `conf.toml` tiada dalam `/samudra/samudra`. Tapi bila run `D:\samudra>python samudra/serve.py`, dia akan jadi
```
Traceback (most recent call last):
  File "D:\samudra\samudra\serve.py", line 9, in <module>
    from server.setup import check_tables
  File "D:\samudra\samudra\server\__init__.py", line 1, in <module>
    from .routes import lemmas, konseps
  File "D:\samudra\samudra\server\routes\lemmas.py", line 6, in <module>
    from samudra import models, schemas
ModuleNotFoundError: No module named 'samudra'
```

Local copy code dah edit buang semua `samudra.module_name`. 

Apa pendapat?

**Comment by Thaza-Kun** [comment]
Pandangan aku, bab import-mengimport dalam Python ni memang agak pelik. Kalau lain sikit cara execute, struktur import dia akan lari. Jadi patah balik ikut repo master pastu pakai `poetry run python ./samudra/serve.py`
